= hawkular-alerts
:source-language: java

[.lead]
*Hawkular Alerting* is the alerts module for Hawkular. It is responsible to define conditions rules over data events
and fire alerts that can be sent by several action plugins.

Hawkular is a modular systems monitoring suite, that consists of several sub-projects for
storing of metrics, alerting on incoming events and more. Those projects are developed
in their own GitHub repositories and integrated in this project.

link:http://www.slideshare.net/ponceballesteros/hawkular-alerting[Hawkular Alerting Introduction].

== Playground for technologies

- Netty
- Reactor
- Plain jar package

== License

Hawkular-Alerts is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
