= hawkular-alerts
:source-language: java

ifdef::env-github[]
[link=https://travis-ci.org/hawkular/hawkular-alerts]
image::https://travis-ci.org/hawkular/hawkular-alerts.svg?branch=master[Build Status,70,18]
endif::[]

[.lead]
*Hawkular Alerting* is the alerts module for Hawkular. It is responsible to define conditions rules over data events
and fire alerts that can be sent by several action plugins.

Hawkular is a modular systems monitoring suite, that consists of several sub-projects for
storing of metrics, alerting on incoming events and more. Those projects are developed
in their own GitHub repositories and integrated in this project.

link:http://www.slideshare.net/ponceballesteros/hawkular-alerting[Hawkular Alerting Introduction].

== Project layout

The project is divided into several modules

[cols=">s,d"]
|=======================
| hawkular-alerts-api |
This is the public Java API for alerts component. +
Users should use only this API to interact with alerts.
| hawkular-alerts-engine |
This is the implementation of the alerts engine. +
It is responsible to manage the alerts definitions and the evaluation of the alerts conditions. +
It includes a rules engine as part of the implementation details.
| hawkular-alerts-rest |
This is a public REST API for alerts component. +
It is a wrapper of the main *hawkular-alerts-api*.
| hawkular-alerts-actions |
Common API for action plugins. +
An action plugin will be deployed as a .war artifact.
| hawkular-alerts-actions-plugins |
Alert actions plugins. +
Main responsabilities are: +
- Publish supported properties. +
- Process actions messages.
| hawkular-alerts-filter-api |
Filter API to query which dataIds are published from triggers defined. +
This info helps to filter and send only the relevant data needed for triggers evaluation.
| hawkular-alerts-bus |
This component is responsible for the communication between the alerts engine and the bus. +
*hawkular-alerts-engine* is decoupled from the bus, so it can be used in other scenarios +
(i.e. standalone, third party alerts system).
| hawkular-alerts-bus-api |
This is the public API for message objects used in *hawkular-alerts-bus*.
|=======================

== Getting started

*Hawkular Alerting* can be built with the following steps:

```shell
    git clone https://github.com/hawkular/hawkular-alerts.git
    cd hawkular-alerts
    ./mvnw clean install
```

== Run examples

* link:https://github.com/hawkular/hawkular-alerts/blob/master/examples/hello-world/README.adoc[Hello World] +
A mandatory Hello World to show basic features of Alerting.

* link:https://github.com/hawkular/hawkular-alerts/blob/master/examples/autoresolve-process/README.adoc[Auto Resolve Process] +
Show how to use AUTORESOLVE conditions to automatically resolve alerts.

* link:https://github.com/hawkular/hawkular-alerts/blob/master/examples/events/README.adoc[Events] +
Tutorial about how to model Events and define conditions for Events evaluation.

* link:https://github.com/hawkular/hawkular-alerts/blob/master/examples/group-triggers/README.adoc[Group Triggers] +
Example about how to manage similar definitions using GroupTriggers as a template.

* link:https://github.com/hawkular/hawkular-alerts/blob/master/examples/webhook/README.adoc[Webhook] +
Hello World example using Webhooks as preferred action.

* link:https://github.com/lucasponce/hawkular-alerts-demo[Monitored Wildfly Server Demo] +
A composite demo where it shows how a Wildfly Server can be monitored at several levels (availability, deployments, application logs) using previous examples in a specific scenario.

== Integration tests

There is a integration test suite that downloads a wildfly server and deploys *hawkular-alerts* with an embedded
cassandra service.
These integration tests can be executed using *-Pitest* profile:

```shell
./mvnw clean install -Pitest
```

== Performance tests

There is a performance test suite focus in the *hawkular-alerts-engine* project.
These tests are not active by default, they can be run using *-Dtest-env=perf* variable:

```shell
./mvnw clean install -Dtest-env=perf
```

== Clustering tests

There is a clustering test suite focus on partition and distribution of the triggers and data across
a topology of nodes.
These test are not active by default, they can be run using *-Denv=cluster* variable:

```shell
./mvnw clean install -Denv=cluster
```

== Building REST API documentation

REST API documentation can be generated using *-Pdocgen* profile. +
The doc is generated under *hawkular-alerts-rest/target* folder.

```shell
./mvnw clean install -Pdocgen
```

== Hawkular Alerting Documentation

* link:http://www.hawkular.org/docs/components/alerts/index.html[Installation and configuration].
* link:http://www.hawkular.org/community/docs/developer-guide/alerts.html[Developer guide]
* link:http://www.hawkular.org/docs/rest/rest-alerts.html[REST API]

== License

Hawkular-Alerts is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
