= hello world

This example shows how to use Hawkular Alerts REST API from a script.

The scripts are written in groovy to make them work from maven in any platorm but those are pretty simple and can be
translated to bash or a different environment easily.

== Running the example

Build a Hawkular Alerts standalone distribution

[source,shell,subs="+attributes"]
----
    cd hawkular-alerts
    mvn clean install -Pstandalone
----

Start the standalone server

[source,shell,subs="+attributes"]
----
    cd hawkular-alerts/hawkular-alerts-rest-tests/target/wildfly-10.0.0.Final/
    bin/standalone.sh
----

Open a new shell to run the hello-world example

[source,shell,subs="+attributes"]
----
    cd hawkular-alerts/examples/hello-world
    mvn validate
----

TIP: By default, Hawkular Alerts will send email notifications using a SMTP server on localhost:25, for demo purposes
 a test smtp server can be used to validate the reception of the emails. Hawkular Alerts has been tested using
 https://nilhcem.github.io/FakeSMTP/[FakeSMTP].

TIP: To run the example against the Hawkular distribution, use the command `mvn validate -Dhawkular`.

== create.definitions.groovy

Create a hello world trigger to two conditions to fire an alert everytime that:

    . numeric data with id "data-x" is less than 5 and
    . numeric data with id "data-y" is greater than 5

Create an action definition to notify by email to admins group with cc to developers team.

== send_data.groovy

Send random data for "data-x" and "data-y" over the REST API.
