= Events

This example shows how to use the events API in Hawkular Alerts.

The scripts are written in groovy to make them work from maven in any platorm but those are pretty simple and can be
translated to bash or a different environment easily.

== Running the examples

Build a Hawkular Alerts standalone distribution

[source,shell,subs="+attributes"]
----
    cd hawkular-alerts
    mvn clean install -Pstandalone
----

Start the standalone server

[source,shell,subs="+attributes"]
----
    cd hawkular-alerts/hawkular-alerts-rest-tests/target/wildfly-10.0.0.Final/
    bin/standalone.sh
----

Open a new shell to run the events examples

[source,shell,subs="+attributes"]
----
    cd hawkular-alerts/examples/events
    mvn validate -Ptutorial1
    ## Change the profile to -Ptutorial2, -Ptutorial3, -Ptutorial4, -Ptutorial5 to run each example
    ## Run mvn validate -Pclean to remove all alerts and events generated previously
----

TIP: By default, Hawkular Alerts will send email notifications using a SMTP server on localhost:25, for demo purposes
 a test smtp server can be used to validate the reception of the emails. Hawkular Alerts has been tested using
 https://nilhcem.github.io/FakeSMTP/[FakeSMTP].

TIP: To run the example against the Hawkular distribution, use the command `mvn validate -Dhawkular`.

== tutorial1

Minimalist example to send and event.

[source,javascript,subs="+attributes"]
----
    {
        "id": "...",        // <A unique identifier for this event, typically an UUID>,
        "ctime": 123,       // <Creation time in milliseconds>,
        "category": "...",  // <Category of the event, used for filtering>,
        "text": "..."       // <Main content of the event>
     }
----

== tutorial2

Adding tags into events offers a structured way to add information used for filtering.

Tags is a map of key/value that can be used to add additional information into the event structure.
All info placed into tags map can be used for filtering.

In the deployments events we are adding:

[source,javascript,subs="+attributes"]
----
    {
        "tags": {
            "operation": "...",     // Type of operation,
            "app": "...",           // Name of the application which is event is referring,
            "container": "..."      // Name of the container where the app is deployed,
        }
    }
----

And in the log events:

[source,javascript,subs="+attributes"]
----
    {
        "tags": {
            "app": "...",           // Name of the application which is event is referring,
        }
    }
----

Events can be queried using the following REST endpoint:

[source,javascript,subs="+attributes"]
----
GET /hawkular/alerts/events                             // For all events
----

[source,javascript,subs="+attributes"]
----
GET /hawkular/alerts/events?categories=DEPLOYMENT,LOG   // Filtering by specific categories
----

[source,javascript,subs="+attributes"]
----
GET /hawkular/alerts/events?tags=app|appA,app|appB      // Filtering by specific tags
----

== tutorial3

Trigger creation to detect undeployment events on containerZ.

Previous triggers with same id are deleted to generate a new one:

[source,javascript,subs="+attributes"]
----
    {
        "id":"detect-undeployment-containerZ",
        "name":"Undeployments detection",
        "action":["email-to-admin-group"],
        "severity":"HIGH"
    }
----

Once trigger is created we can add a condition to fire an alert on undeployment events for containerZ:

[source,javascript,subs="+attributes"]
----
    {
        "triggerMode":"FIRING",
        "type":"EVENT",
        "dataId":"events-source",
        "expression":"tags.operation == 'undeployment',tags.container == 'containerZ'"
    }
----

The condition must have a dataId to define an events source. This means that only events with dataId ==
"events-source" will be evaluated against this rule.

This example sends multiple random events in a loop.

Note that deployment events are marked with dataId equals to "events-source'.

[source,javascript,subs="+attributes"]
----
    {
        "id": "...",        // <A unique identifier for this event, typically an UUID>,
        "ctime": 123,       // <Creation time in milliseconds>,
        "category": "...",  // <Category of the event, used for filtering>,
        "text": "...",      // <Main content of the event>
        "dataId": "...",    // <Define a source of events>
                            // This dataId is used in trigger conditions to indicate which
                            // source of events should be used for evaluation
     }
----

This means that only deployment events are processed for alerting.

A dataId is active if there is a reference of it on a trigger condition. Only events with dataId actives are
evaluated by the engine.

== tutorial4

Trigger creation to detect undeployments events on containerZ and errors on log.

This trigger won't have any action defined, it will only create an alert.

[source,javascript,subs="+attributes"]
----
    {
        "id":"detect-undeployment-containerZ-with-errors",
        "name":"Undeployments detection with Errors",
        "severity":"HIGH"
    }
----

A first Trigger is created now with two conditions, each condition has a different dataId to make sure that only events
with same dataId are evaluated against its specific condition.

[source,javascript,subs="+attributes"]
----
  [
    {
        "triggerMode":"FIRING",
        "type":"EVENT",
        "dataId":"events-deployments-source",
        "expression":"tags.operation == 'undeployment',tags.container == 'containerZ'"
     },
    {
        "triggerMode":"FIRING",
        "type":"EVENT",
        "dataId":"events-logs-source",
        "expression":"text starts 'ERROR'"
    }
  ]
----

A second trigger will be created to detect events generated for the first trigger and send actions.

[source,javascript,subs="+attributes"]
----
    {
        "id":"chained-trigger",
        "name":"Chained trigger",
        "description":"Show how to define a trigger using Events generated from other trigger",
        "action":["email-to-admin-group"],
        "severity":"HIGH"
    }
----

This chained trigger uses an EVENT condition pointing as the previous trigger as dataId. If no expression is added
the condition will be evaluated when a new Event is created.

[source,javascript,subs="+attributes"]
----
    {
        "triggerMode":"FIRING",
        "type":"EVENT",
        "dataId":"detect-undeployment-containerZ-with-errors"
    }
----

Alerts are a specific type of events, so EVENT condition can be used to detect new alerts generated by the engine.

This example sends multiple random events in a loop.

Deployment events are assigned with "events-deployments-source" dataId to make sure that only are evaluated with
its specific conditions.

Log events are assigned with "events-log-source" dataId to define a different events source and make sure that these
events are only evaluated with its specific conditions.

== tutorial5

Trigger creation to detect undeployments events on containerZ and errors on log similar as
tutorial4 example, but now it will generate a new simple Event.

[source,javascript,subs="+attributes"]
----
    {
        "id":"detect-undeployment-containerZ-with-errors",
        "name":"Undeployments detection with Errors",
        "severity":"HIGH",
        "eventType":"EVENT"
    }
----

Alerts will be generated just by the chained trigger.

This example sends multiple random events in a loop similar as tutorial4.

== clean

WARNING: Delete all alerts and events