
== Lesson 02 - First Alert

We define a _Trigger_ in Hawkular Alerting (hAlerting) to fire an _Alert_ when its condition set evaluates to true.  Let's start with the most simple trigger and build it up with a few common options...

----
Trigger
  id:   lesson-02
  name: Lesson 02
----

* hAlerting supports multi-tenancy, so everything is assigned to a tenant.
** The tenantId will be assigned in the REST request, via an HTTP header.
** In the tutorial we'll put everything in the _tutorial_ tenant.
* TriggerIds must be unique within the tenant.
* Name is required, but used for display.

The trigger above uses defaults for all options and it does not yet define any conditions. Using your preferred mechanism (curl, Chrome ARC, etc), let's create the trigger via the REST API:

[cols="1,5l"]
|===
|Request
|POST http://localhost:8080/hawkular/alerts/triggers

|HTTP Headers
|Hawkular-Tenant: tutorial
Content-Type: application/json

|Body
|
{
"id":"lesson-02",
"name":"Lesson 02"
}
|===

The request response returns the new trigger.  But just to become more familiar with the REST API, let's fetch the trigger definition and let's look at some of the defaults and missing information:

[cols="1,5l"]
|===
|Request
|GET http://localhost:8080/hawkular/alerts/triggers/lesson-02

|HTTP Headers
|Hawkular-Tenant: tutorial
Content-Type: application/json
|===

.Response
----
{
"tenantId": "tutorial",
"id": "lesson-02",
"name": "Lesson 02",
"type": "STANDARD",
"eventType": "ALERT",
"eventCategory": null,
"eventText": null,
"severity": "MEDIUM",
"autoDisable": false,
"autoEnable": false,
"autoResolve": false,
"autoResolveAlerts": true,
"autoResolveMatch": "ALL",
"enabled": false,
"firingMatch": "ALL",
"source": "_none_"
}
----

We'll ignore some fields for now, but a couple of settings are important:

* Severity
** HAlerting has LOW, MEDIUM, HIGH for alert severity
* AutoDisable
** If true the trigger disables after it fires, this can prevent alert floods.
** We'll turn this on a little later...
* AutoEnable
** If true the trigger enables itself when it no longer has unresolved alerts.
** This avoids having to remember to re-enable a trigger after an issue is resolved.
* Enabled
** The trigger won't fire unless it's enabled.
** We'll set this to true when we have our trigger fully defined.

=== Conditions

The big thing we're missing are the conditions that define when the trigger should fire an alert.  HAlerting offers http://www.hawkular.org/community/docs/developer-guide/alerts-v2.html#\_conditions[many different condition types] out of the box.  Each condition performs evaluations against incoming data to see if it is satisfied.  A condition type found in virtually any alerting system is __Threshold__, so let's start with a threshold condition for our tutorial. Note that the body supports a list of conditions but for now we'll only use one.

[cols="1,5l"]
|===
|Request
|PUT http://localhost:8080/hawkular/alerts/triggers/lesson-02/conditions/FIRING

|HTTP Headers
|Hawkular-Tenant: tutorial
Content-Type: application/json

|Body
|
[{
"type":"THRESHOLD",
"triggerId":"lesson-02",
"dataId":"gauge-1",
"operator":"GTE",
"threshold":50
}]
|===

.Response
----
{
"tenantId": "tutorial",
"triggerId": "lesson-02",
"triggerMode": "FIRING",
"type": "THRESHOLD",
"conditionSetSize": 1,
"conditionSetIndex": 1,
"conditionId": "tutorial-lesson-02-FIRING-1-1",
"dataId": "gauge-1",
"operator": "GTE",
"threshold": 50
}
----

This is a PUT request, note that it will replace any existing condition set on the trigger, for the triggerMode. As for triggerMode, and other fields:

* TriggerMode specifies whether these are _Firing_ conditions or _AutoResolve_ conditions.
** The trigger mode is specified in the url path.
** Firing mode conditions specify when the trigger should fire an alert.
** We'll talk about AutoResolve later.
* DataId specifies the data on which this condition evaluates.
** We want this threshold to evaluate against our gauge-1 metric (generated by our tutorial-data.sh script).
* The remaining fields are specific to the Threshold condition type: _threshold_ and _operator_.
** Different condition types have different type-specific fields.
** You can http://www.hawkular.org/docs/rest/rest-alerts.html#\_data\_types[look here in the REST API] to see the type-specific fields.

=== Fire!

OK, our trigger now has a condition.  Let's enable our trigger and watch it fire.  A trigger enable is like any other trigger update, just update the trigger with the desired settings.  While we're at it, let's also turn on the autoDisable feature we saw above:

[cols="1,5l"]
|===
|Request
|PUT http://localhost:8080/hawkular/alerts/triggers/lesson-02

|HTTP Headers
|Hawkular-Tenant: tutorial
Content-Type: application/json

|Body
|
{
"id":"lesson-02",
"name":"Lesson 02",
"enabled":true,
"autoDisable":true
}
|===

Now, let's start our data pump for the gauge-1 metric.  Note that only data generated after the trigger is enabled will be evaluated.

`> ./tutorial-data.sh`

It may take a few moments for our alert to fire.  The threshold is 50 and we generate random numbers between 0 and 100 at 5s intervals.  In the command window running the data generator you can wait to see a value >= 50 for gauge-1.  When you do, make this request to query for lesson-02 alerts, and you should get a similar response:

[cols="1,5l"]
|===
|Request
|GET http://localhost:8080/hawkular/alerts?triggerIds=lesson-02

|HTTP Headers
|Hawkular-Tenant: tutorial
Content-Type: application/json
|===

.Response
----
{
"eventType": "ALERT",
"tenantId": "tutorial",
"id": "lesson-02-1488233569253-b50df522-37db-4ba7-90a3-2799066b3e6b",
"ctime": 1488233569253,
"dataSource": "_none_",
"dataId": "lesson-02",
"category": "ALERT",
"text": "Lesson 02",
"trigger": {
   "tenantId": "tutorial",
   "id": "lesson-02",
   "name": "Lesson 02",
   "type": "STANDARD",
   "eventType": "ALERT",
   "eventCategory": null,
   "eventText": null,
   "severity": "MEDIUM",
   "autoDisable": true,
   "autoEnable": false,
   "autoResolve": false,
   "autoResolveAlerts": true,
   "autoResolveMatch": "ALL",
   "enabled": true,
   "firingMatch": "ALL",
   "source": "_none_"
},
"dampening": {
   "tenantId": "tutorial",
   "triggerId": "lesson-02",
   "triggerMode": "FIRING",
   "type": "STRICT",
   "evalTrueSetting": 1,
   "evalTotalSetting": 1,
   "evalTimeSetting": 0,
   "dampeningId": "tutorial-lesson-02-FIRING"
},
"evalSets": [
  [{
   "evalTimestamp": 1488233569190,
   "dataTimestamp": 1488233566391,
   "type": "THRESHOLD",
   "condition": {
      "tenantId": "tutorial",
      "triggerId": "lesson-02",
      "triggerMode": "FIRING",
      "type": "THRESHOLD",
      "conditionSetSize": 1,
      "conditionSetIndex": 1,
      "conditionId": "tutorial-lesson-02-FIRING-1-1",
      "dataId": "gauge-1",
      "operator": "GTE",
      "threshold": 50
      },
   "value": 93
   }],
],
"severity": "MEDIUM",
"status": "OPEN",
"lifecycle": [{
   "status": "OPEN",
   "user": "system",
   "stime": 1488233569253
   }],
}
----

You can see that an Alert carries a lot of information to help understand its origin. The alert fields themselves are probably clear.  The trigger is attached for reference.  We'll cover dampening and lifecycle in the next few lessons.  For now, look more closely at the _evalSets_ field.  This field explains why the trigger fired the alert.  Because the `lesson-02` trigger has only one condition, each evalSet has only one condition evaluation.  And because we are firing as soon as we have a single true evaluation (no dampening), we only have one evalSet.  In this case we can see that a `gauge-1` datapoint was received with a value of 93. because `93 GTE 50` is true, the trigger fired.

=== Exercise

At this point you may feel comfortable creating a trigger and trying some of the http://www.hawkular.org/community/docs/developer-guide/alerts-v2.html#\_conditions[other condition types] offered out of the box by hAlerting.

When you are ready, move on to the next lesson.

link:lesson-03-dampening.adoc[Lesson 03 - Dampening]

link:../README.adoc[Tutorial Home]

