
== Lesson 07 - Events

In previous lessons we've learned about defining triggers and how those triggers fire alerts.  We've learned about the alert lifecycle and how actions can be executed on lifecycle changes.  As we discuss in our http://www.hawkular.org/community/docs/developer-guide/alerts-v2.html#\_alerting\_philosophy[alerting philosophy], alerts should be generated infrequently and with great care, in order to maintain their relevance. In Hawkular Alerting a trigger can also generate an __Event__. Events are used to record interesting system happenings that don't justify an alert, or may help build evidence towards a future alert.

Events don't require immediate human intervention, don't need to be resolved, and don't have life-cycle.  They just record a happening at some point in time.  There are multiple ways to get events into the system, and several things that can be done with them.  Let's work through an example...

=== Event Example

In this example we'll try and combine several aspects of using events:

* Define a trigger that generates an event based on incoming metrics.
* Define a trigger that generates an alert based on seeing two different events.
* Generate an event explicitly via the REST API.

==== Trigger that Generates an Event Based on Metric Data

A trigger can generate an event in exactly the same way it generates an alert.  The difference is that you need to set `eventType=EVENT`.  By default `eventType=ALERT`. There are also some other fields you can set, like `eventCategory` and `eventText`. Let's define a simple trigger than fires an event based on a threshold violation.

[cols="1,5l"]
|===
|Request
|POST http://localhost:8080/hawkular/alerts/triggers/trigger

|HTTP Headers
|Hawkular-Tenant: tutorial
Content-Type: application/json

|Body
|
{
"trigger": {
  "tenantId": "tutorial",
  "id": "lesson-07-trigger-event",
  "name": "Lesson 07 Trigger",
  "description": "Generates an event if gauge-1 reads high",
  "eventType": "EVENT",
  "eventCategory": "tutorial (this defaults to TRIGGER)",
  "eventText": "tutorial (this defaults to the trigger description)",
  "autoDisable": false,
  "enabled": true,
  "firingMatch": "ALL",
  "tags": {
    "lesson": "7"
  }
},
"conditions": [
  {
    "triggerMode": "FIRING",
    "type": "THRESHOLD",
    "dataId": "gauge-1",
    "operator": "GTE",
    "threshold": 80
  }
]
}
|===

==== Trigger that Generates an Alert Based on Event Data

The fundamental lesson here is that _events are also data_.  In the same way that we have numeric data and string data to use in condition matching, we can also use events as data for condition matching.  The trigger below uses two _EventConditions_ for its firing criteria.

[cols="1,5l"]
|===
|Request
|POST http://localhost:8080/hawkular/alerts/triggers/trigger

|HTTP Headers
|Hawkular-Tenant: tutorial
Content-Type: application/json

|Body
|
{
"trigger": {
  "tenantId": "tutorial",
  "id": "lesson-07",
  "name": "Lesson 07 Threshold",
  "description": "Generates an an alert if we have a lesson-07-threshold event and also a lesson-07-alarm event",
  "eventType": "ALERT",
  "autoDisable": true,
  "enabled": true,
  "firingMatch": "ALL",
  "tags": {
    "lesson": "7"
  }  
},
"conditions": [
  {
    "triggerMode": "FIRING",
    "type": "EVENT",
    "dataId": "lesson-07-trigger-event",
    "expression": "category contains 'TRIGGER',text starts 'tutorial',tags.lesson == '7'"  },
  {
    "triggerMode": "FIRING",
    "type": "EVENT",
    "dataId": "lesson-07-api-event",
    "expression": "category contains 'alarm',text contains 'sensor-1-hot',tags.lesson == '7'"
  }
]
}
|===

So now we have the trigger that can generate an alert.  To fire it needs two different events, one that will be generated by a trigger, based on metric data, and another that must be sent via the REST API.  We can see that because events are data they can set a dataId, and the dataId is used to tie the event to the condition. Furthermore the event condition supplies an expression that must be satisfied for the condition to match.  A full description of the expression definition http://www.hawkular.org/docs/rest/rest-alerts.html#EventCondition[can be found here].

TIP: Trigger-generated events have the dataId set to the id of the generating trigger. See above how the first condition has `"dataId": "lesson-07-trigger-event"`.

We can turn on the data pump and it will start generating events, but it won't fire an alert because only one of lesson-07's event conditions will be satisfied.

`> ./tutorial-data.sh`

Trigger-generated events should appear fairly frequently.  To check for events try:

[cols="1,5l"]
|===
|Request
|GET http://localhost:8080/hawkular/alerts/events?tagQuery=lesson=7

|HTTP Headers

|Hawkular-Tenant: tutorial
Content-Type: application/json
|===

Alerts should not yet appear. To check for alerts try:

[cols="1,5l"]
|===
|Request
|GET http://localhost:8080/hawkular/alerts?tagQuery=lesson=7

|HTTP Headers
|Hawkular-Tenant: tutorial
Content-Type: application/json
|===

Now, let's inject an alert via the REST API, from the outside world.  In this case we'll simulate a sensor sending in an alarm about a high temperature...

[cols="1,5l"]

|===
|Request
|POST http://localhost:8080/hawkular/alerts/events

|HTTP Headers
|Hawkular-Tenant: tutorial
Content-Type: application/json

|Body
|
{
  "id": "UniqueEventId1",
  "dataId": "lesson-07-api-event",
  "category": "alarm",
  "text": "sensor-1-hot",
  "context": {
    "room": "data-center-1"
  },
  "tags": {
    "lesson": "7"
  }
}
|===

Some things to note about the injected event:

* Each event requires a unique id (within the tenant).
* The dataId ties this event to the EventCondition on our trigger.
* The category, text and tag values are all used in our EventCondition expression.
* We can always supply context to better classify an event (and other entities used in HAlerting).

Shortly after this event is posted we should see an alert for trigger `lesson-07`.  We now have both of the required events in working memory and the alert will be generated. Remember that in order to explain why an alert was fired, `alert.evalSets` always provides the data contributing to the alert. In this case you can see both of the contributing events are included.  Furthermore, since one of the events was itself fired from an alert, its evalSets are also provided.

TIP: Not every API-injected event needs to be processed by the engine.  Events without a dataId, or a dataId that is not used in any enabled trigger, is ignored by the engine and will just be persisted.

TIP: Not every API-injected event needs to be persisted. The event we injected above was processed by the engine and persisted. The following request will fetch it from the database: `GET http://localhost:8080/hawkular/alerts/events?categories=alarm&tagQuery=lesson=7`. To inject a non-persisted event change `POST /hawkular/alerts/events` to `POST /hawkular/alerts/events/data`.  Using the `/data` variant is not useful if the event does not have a dataId used in a defined trigger.

=== Alerts are Events

Above we defined an event as an alert without life-cycle.  Put another way, an alert is an event _with_ life-cycle.  Alerts and events are persisted separately.  A fetch for alerts will not return events and vice-versa. But, there are times when the two are handled in the same way.

===== Alerts are Data

Just as an event can be used in an EventCondition, alerts can also be used.  When an alert is generated the dataId is set to the alertId and if that dataId is used in an enabled trigger, the alert is fed back into the engine as data for the relevant EventConditions. Relevant EventCondition fields are set like this for an alert:

* dataId = alert.id
* category = alert.eventCategory if set, otherwise "ALERT"
* text = alert.eventText if set, otherwise alert.description if set, otherwise alert.name

===== Events and Actions

Actions are typically associated with alerts.  But alerts are events, and actions in Hawkular Alerting operate on events. So, although events don't have life-cycle they can execute actions. Actions can be defined on an event trigger.  The actions will be executed on event creation.  Because actions are tied to triggers it's not directly possible to execute actions for events injected via the API.  But it can be done indirectly.  Because events are data, it is possible to define a trigger that will fire on an injected event, generating a complementary event and executing actions.

=== Events Summary

In this example we've seen that:

* Events can be generated by triggers.
* Events can be injected via the API.
* Events are themselves data and used in EventConditions.
* Alerts are Events.

Using Events and Alerts together can be a powerful combination. In general a system will record many more events than alerts.  The events can be used for any number of things, including timelines, graphing, auditing, and to build evidence for alerts.  In future lessons we'll learn about a powerful extension for reasoning against aggregated alerts in a sliding window of time, and also how to set up a _watcher_ for streaming new and updated events and alerts to your client.

When you are ready, move on to the next lesson.  It talks about how to complement your out-of-the-box condition types with custom, external conditions.  Or, if you want to work more with events, https://github.com/hawkular/hawkular-alerts/tree/master/examples/events[check out this example].

Otherwise, it's time to move on...

link:lesson-08-alerters.adoc[Lesson 08 - External Alerters]

link:../README.adoc[Tutorial Home]

