== Lesson 03 - Dampening

In lesson 02 we created a trigger and fired an alert.  We created a threshold condition to look for gauge-1 datapoints GTE 50.  And the first datapoint that evaluated true fired the trigger.  But often we, and especially an engineer on call, don't want an alert based on a single outlier. Instead, we want to identify a sustained or degrading issue.  In Hawkular Alerting (hAlerting) we do this via _Trigger Dampening_.

Under the covers every trigger has dampening applied, it's just that by default we apply _Strict-1_ dampening, meaning that we just need 1 consecutive true evaluation of the conditions. In other words, _Strict-1_ dampening means the trigger fires every time the condition set evaluates to true. _Strict_ dampening means we need consecutive true evaluations in order to fire the trigger.  This is commonly used to prevent alerting on a sudden spike.  We can apply strict-count or strict-time based dampening.  Strict-count means N consecutive true evaluations.  Strict-time means all true evaluations for some minimum period of time.

=== Condition Evaluations

Note that an _evaluation_ happens whenever we have new incoming data that allows us to evaluate the condition set.  Triggers can define _ALL_ or _ANY_ matching to the condition set.  _ALL_ is the default. It means that using the most recent data available for each condition, each condition must individually evaluate to true for the condition set to evaluate to true, as a whole. _ANY_ matching is what you would expect, only one of multiple conditions must evaluate to true for the condition set to be true.

Dampening is concerned with *condition set* evaluations, not individual conditions.

=== Relaxed Dampening

Sometimes strict dampening is, well, too strict.  In that case we have relaxed dampening, again in the count and time varieties.  Relaxed-count means N out of M consecutive true evaluations.  Relaxed-time means N true evaluations in some minimum period of time.  One note on relaxed time, unless data is reported frequently enough the dampening may never be satisfied.  To varying degrees the time based dampening options are tied to the reporting intervals of the relevant dataIds.

You can find http://www.hawkular.org/community/docs/developer-guide/alerts-v2.html#_trigger_dampening[more details on dampening options here].

=== Example

Now, let's add to the trigger example we started in lesson 02.

We'll do two things:

* To show a multi-condition trigger let's add a _Rate_ condition on our counter-1 metric.
** Remember, this metric increases by 0..5 every 5s, which extrapolates to 0..60 every minute.  We'll look for GTE 30 per minute.
* Add Strict-2 dampening.
** That means the condition set (both conditions) must be true on two consecutive evaluations.
** Remember, when data arrives at different times, the most recent data for each condition is used for the evaluations.

In case you didn't just run lesson 02, we'll start with a clean slate.

. If necessary, revisit lesson 01.  Restart your docker-compose via:
.. `> sudo docker-compose down`
.. `> sudo docker-compose up`
. If your data pump script, tutorial-data.sh is running, stop it.

  
Let's create our trigger introducing a new endpoint, _Full trigger_ endpoints are convenient for dealing with complete trigger definitions. We can create, fetch, import and export full triggers.  Here, we'll use a POST to create the full trigger:

[cols="1,5l"]
|===
|Request
|POST http://localhost:8080/hawkular/alerts/triggers/trigger

|HTTP Headers
|Hawkular-Tenant: tutorial
Content-Type: application/json

|Body
|
{
"trigger": {
  "tenantId": "tutorial",
  "id": "lesson-03",
  "name": "Lesson 03",
  "description": "A useful description that can also include resolution instructions or links",
  "autoDisable": true,
  "enabled": true,
  "firingMatch": "ALL"
},
"conditions": [
  {
    "triggerMode": "FIRING",
    "type": "THRESHOLD",
    "dataId": "gauge-1",
    "operator": "GTE",
    "threshold": 50
  },
  {
    "triggerMode": "FIRING",
    "type": "RATE",
    "dataId": "counter-1",
    "direction": "INCREASING",
    "period": "MINUTE",
    "operator": "GTE",
    "threshold": 30
  }
],
"dampenings": [
  {
     "triggerMode": "FIRING",
     "type": "STRICT",
     "evalTrueSetting": 2,
     "evalTotalSetting": 2
  }
]
}
|===

Now, let's start our data pump and wait for the trigger to fire.  It may take few moments because we need both conditions to evaluate to true, and because of our strict-2 dampening, the conditions must evaluate to true two times consecutively.

`> ./tutorial-data.sh`

The following request queries for lesson-03 alerts. Eventually you should get a single alert. Remember, the trigger has `autoDisable=true`, making it disable after firing.  
You should get an alert similar to the response below.  When you do you can stop the data pump:

[cols="1,5l"]
|===
|Request
|GET http://localhost:8080/hawkular/alerts?triggerIds=lesson-03

|HTTP Headers
|Hawkular-Tenant: tutorial
Content-Type: application/json
|===

.Response (some parts omitted for brevity)
----
{
"tenantId": "tutorial",
"id": "lesson-03-1488378577704-fbf2d6bf-955e-44e7-a2cd-021efe753d63",
"ctime": 1488378577704,
"dataId": "lesson-03",
"category": "ALERT",
"text": "A useful description that can also include resolution instructions or links",
"trigger": {
    omitted
},
"dampening": {
  "tenantId": "tutorial",
  "triggerId": "lesson-03",
  "triggerMode": "FIRING",
  "type": "STRICT",
  "evalTrueSetting": 2,
},
"evalSets": [
  [{
   "evalTimestamp": 1488378573681,
   "dataTimestamp": 1488378571537,
   "type": "RATE",
   "condition": {
     "dataId": "counter-1",
     "direction": "INCREASING",
     "period": "MINUTE",
     "operator": "GTE",
     "threshold": 30
   },
   "previousValue": 42,
   "value": 45,
   "previousTime": 1488378566424,
   "time": 1488378571537,
   "rate": 35.20438098963427
   },
   {
   "evalTimestamp": 1488378573681,
   "dataTimestamp": 1488378571537,
   "type": "THRESHOLD",
   "condition": {
     "dataId": "gauge-1",
     "operator": "GTE",
     "threshold": 50
   },
   "value": 90
   }
  ],,
  [{
   "evalTimestamp": 1488378577686,
   "dataTimestamp": 1488378576626,
   "type": "THRESHOLD",
   "condition": {
     omitted, same as above
   },
   "value": 75
   },
   {
   "evalTimestamp": 1488378577687,
   "dataTimestamp": 1488378576626,
   "type": "RATE",
   "condition": {
     omitted, same as above
   },
   "previousValue": 45,
   "value": 50,
   "previousTime": 1488378571537,
   "time": 1488378576626,
   "rate": 58.950677932796225
   }
  ],
],
"severity": "MEDIUM",
"status": "OPEN",
"lifecycle": [{
  omitted
  }
}
----

The important thing to see in this response is that the _evalSets_ field now has two entries. Our lesson-02 alert had only one entry. Here we are using Strict-2 dampening, whereas the lesson-02 trigger used default, Strict-1, dampening. Strict-2 requires two true evaluations and we now see two evaluation set entries.  And because the lesson-03 trigger has two conditions, each set has two condition evaluations.  And finally, because the trigger uses _ALL_ matching, every condition evaluation must be true.

When you are ready, move on to the next lesson.

link:lesson-04-ui.adoc[Lesson 04 - UI]

link:../README.adoc[Tutorial Home]

