= Gnocchi Integration

This example shows how to integrate Gnocchi with Hawkular Alerting.

====
The scripts used for this example are written in *bash* and tested on Linux platforms. +
Those are pretty simple and can be translated a different environment easily.
====

== Install a Gnocchi demo environment

For this example we use the link:https://github.com/gnocchixyz/gnocchi-docker/[gnocchi-docker] repository.

Check it out and perform a

[source,shell]
----
  docker-compose up
----

== Install Hawkular Alerting

For this example we use use the link:https://hub.docker.com/r/hawkular/hawkular-alerts[docker hawkular-alerts] image.

Run a command

[source,shell]
----
  docker run -i -t -p 8080:8080 hawkular/hawkular-alerts
----

== Create Triggers definitions

Run the script

[source,shell]
----
  ./create-definitions.sh
----

This script will create the following triggers on Gnocchi systems

[source,shell]
----
{
  "triggers":[
    {
      "trigger":{
        "id": "high-load",
        "name": "High Load",
        "description": "Alert when mean of load is > 2. Resolved automatically.",
        "severity": "HIGH",
        "enabled": true,
        "autoResolve": true,
        "autoResolveAlerts": true,
        "tags": {
          "Gnocchi": "Localhost instance" // <1>
        },
        "context": {
          "metric.names": "load@load-0,load@load-1,load@load-2", // <2>
          "metric.aggregation":"load=mean(load@load-0,load@load-1,load@load-2)" // <3>
        },
        "actions":[
          {
            "actionPlugin": "email",
            "actionId": "email-to-admins"
          }
        ]
      },
      "conditions":[
        {
          "triggerMode": "FIRING",
          "type": "THRESHOLD",
          "dataId": "load",
          "operator": "GT",
          "threshold": 2
        },
        {
          "triggerMode": "AUTORESOLVE",
          "type": "THRESHOLD",
          "dataId": "load",
          "operator": "LTE",
          "threshold": 2
        }
      ]
    },
    {
      "trigger":{
        "id": "high-user-cpu",
        "name": "High User CPU",
        "description": "Alert when mean of user cpu is > 3.7M. Investigate manually.",
        "severity": "MEDIUM",
        "enabled": true,
        "tags": {
          "Gnocchi": "Localhost instance" // <1>
        },
        "context": {
          "metric.names.regexp": "cpu-.@cpu-user-.*", // <2>
          "metric.aggregation":"cpu-user=mean(cpu-.@cpu-user-.*)" // <3>
        },
        "actions":[
          {
            "actionPlugin": "email",
            "actionId": "email-to-admins"
          }
        ]
      },
      "conditions":[
        {
          "type": "THRESHOLD",
          "dataId": "cpu-user",
          "operator": "GT",
          "threshold": 3700000
        }
      ]
    },
    {
      "trigger":{
        "id": "low-free-memory",
        "name": "Low Free Memory",
        "description": "Alert when Free Memory < 20% Memory Used.",
        "severity": "CRITICAL",
        "enabled": true,
        "tags": {
          "Gnocchi": "Localhost instance" // <1>
        },
        "context": {
          "metric.names": "memory@memory-used-0,memory@memory-free-0" // <2>
        },
        "actions":[
          {
            "actionPlugin": "email",
            "actionId": "email-to-admins"
          }
        ]
      },
      "conditions":[
        {
          "type": "COMPARE",
          "dataId": "memory@memory-free-0",
          "operator": "LT",
          "dataId2": "memory@memory-used-0",
          "data2Multiplier": 0.2
        }
      ]
    }
  ],
  "actions":[
    {
      "actionPlugin": "email",
      "actionId": "email-to-admins",
      "properties": {
        "to": "admins@hawkular.org"
      }
    }
  ]
}
----

<1> Triggers tagged with _Gnocchi_ will be managed by the alerter to collect metrics from a Gnocchi system
<2> Gnocchi metrics are identified by metric names
<3> These triggers use aggregated metrics which will be used in the conditions as dataIds

== Visualize Alerts on Hawkular

Access to the link:http://localhost:8080/hawkular/alerts/ui[Hawkular Alerting Console] to get details of the Alerts and Triggers.

