= Group Triggers

This example shows how to use Hawkular Alerting REST API from a script.

The scripts are written in groovy to make them work from maven in any platorm but those are pretty simple and can be
translated to bash or a different environment easily.

== Running the example

Build a Hawkular Alerting standalone distribution

[source,shell,subs="+attributes"]
----
    cd hawkular-alerts
    mvn clean install
----

Start the standalone server

[source,shell,subs="+attributes"]
----
    cd hawkular-alerts/hawkular-alerts-rest-tests/target/wildfly-10.0.0.Final/
    bin/standalone.sh
----

Open a new shell to run the hello-world example

[source,shell,subs="+attributes"]
----
    cd hawkular-alerts/examples/hello-world
    mvn validate
----

[TIP]
.Test Email server
==================
By default, Hawkular Alerting will send email notifications using a SMTP server on localhost:25, for demo purposes
 a test smtp server can be used to validate the reception of the emails. +
  +
Hawkular Alerting has been tested using
  https://nilhcem.github.io/FakeSMTP/[FakeSMTP]. +
  +
A GUI SMTP server can be set up with these steps:
[source,shell,subs="+attributes"]
----
    git clone https://github.com/Nilhcem/FakeSMTP
    cd FakeSMTP
    mvn clean install -DskipTests
    cd target
    sudo java -jar fakeSMTP-*.jar
----
==================

== create_group_trigger.groovy

Create a group trigger with two conditions.

This group trigger will be used as template/parent to create new members/children triggers.

This group trigger has two conditions, using generic label for dataIds:

    . numeric data with id "generic-data-x" is less than 5 and
    . numeric data with id "generic-data-y" is greater than 5

When members are created, labels used for dataIds are replaced by the definitive dataIds.

== create_members.groovy

Create new members from a group trigger as base.

On member creation, specific details for each member are supplied.

Generic labels used for dataId in the group trigger are personalized on each member:

    . "generic-data-x" -> "data-x-for-member-${i}"
    . "generic-data-y" -> "data-y-for-member-${i}"

== update_group_trigger.groovy

A change on the group trigger is propagated into the members.

For example, a change on the threshold of the conditions:

    . numeric data with id "generic-data-x" is less than 10 and
    . numeric data with id "generic-data-y" is greater than 10

New thresholds are propagated on all members of the group trigger.

== clean_all.groovy

A delete of a group trigger can also delete all members.

It is also possible to delete a group trigger but maintain the members, in that case the existing members are updated to ORPHAN type.


