= WebHook

This example shows how to use Hawkular Alerting REST API in Hawkular Alerts.

The scripts are written in groovy to make them work from maven in any platorm but those are pretty simple and can be
translated to bash or a different environment easily.

== Running the example

Build a Hawkular Alerting standalone distribution

[source,shell,subs="+attributes"]
----
    cd hawkular-alerts
    mvn clean install
----

Start the standalone server

[source,shell,subs="+attributes"]
----
    cd hawkular-alerts/hawkular-alerts-rest-tests/target/wildfly-10.0.0.Final/
    bin/standalone.sh
----

Open a new shell to run the webhook example

[source,shell,subs="+attributes"]
----
    cd hawkular-alerts/examples/webhook
    mvn validate
----

== create_definitions.groovy

Create a hello world trigger with two conditions to fire an alert everytime that:

    . numeric data with id "data-x" is less than 5 and
    . numeric data with id "data-y" is greater than 5

Create an action definition to notify by a webhook url.

It will use the ping endpoint `http://localhost:8080/hawkular/actions/webhook/ping` included into the webhook plugin.

== send_data.groovy

Send random data for "data-x" and "data-y" over the REST API.
