= WebHook

This example shows how to use Hawkular Alerting REST API in Hawkular Alerts.

The scripts are written in groovy to make them work from maven in any platorm but those are pretty simple and can be
translated to bash or a different environment easily.

== Running the example

Build a Hawkular Alerting standalone distribution

[source,shell,subs="+attributes"]
----
    cd hawkular-alerts
    mvn clean install -Pstandalone
----

Start the standalone server

[source,shell,subs="+attributes"]
----
    cd hawkular-alerts/hawkular-alerts-rest-tests/target/wildfly-10.0.0.Final/
    bin/standalone.sh
----

Open a new shell to run the webhook example

[source,shell,subs="+attributes"]
----
    cd hawkular-alerts/examples/webhook
    mvn validate
----

TIP: To run the example against the Hawkular Services distribution, you must install the webhook plugin manually.

[source,shell,subs="+attributes"]
----
    # Build the Hawkular Alerting without any flag to prepare the plugin for hawkular services distribution
    mvn clean install
    # Copy the plugin into hawkular-services distribution
    cp hawkular-alerts-actions-plugins/hawkular-alerts-actions-webhook/target/hawkular-alerts-actions-webhook.war \
    $HAWKULAR_SERVICES/modules/system/layers/hawkular/org/hawkular/nest/main/deployments/
----

== create_definitions.groovy

Create a hello world trigger to two conditions to fire an alert everytime that:

    . numeric data with id "data-x" is less than 5 and
    . numeric data with id "data-y" is greater than 5

Create an action definition to notify by a webhook url.

== send_data.groovy

Send random data for "data-x" and "data-y" over the REST API.
